### PR TITLE
Dark Mode Feature Added

### LINKED ISSUE #14: [Feature]:Enable Dark Mode
Almost every website today has a dark mode feature as it reduces eye strain and improves readability in low-light conditions.

Introducing Dark and Light Mode Feature in the website would enhance it's features.

### PR DESCRIPTION
**Pull request by geek-nikhil**
->This PR Adds The Dark Mode Feature <-
Fixes  #14 

##Before
Screenshot (152)

##After
Screenshot (154)

### CODE REVIEW

**Comment by 1010varun** [comment]
image
@geek-nikhil please correct the spelling of true weather its tru weather

**Comment by geek-nikhil** [comment]
@1010varun please check the changes

**Comment by 1010varun** [comment]
@geek-nikhil its not attractive, kindly make some changes

**Comment by 1010varun** [comment]
@geek-nikhil please check for the failing test cases

**Comment by geek-nikhil** [comment]
@1010varun, I have updated the build file. What could be the reason for the error? Please try it once.

**Comment by geek-nikhil** [comment]
fsrgfnzrskgnrskjg

**Comment by 1010varun** [comment]
image
fix this

**Comment by 1010varun** [comment]
solved

**Pull request closed without merging**
